version: "3.7"

services:
  checkout_app:
    build:
      context: ./checkout-system
    environment:
      MESSAGE_STORE_URI: postgresql://message_store@message_db:5432/message_store
    command: "./bin/wait-for-it.sh message_db:5432 -t 60 -s -- ./bin/wait-for-it.sh read_model_db:5433 -t 60 -s -- npm run dev"
    ports:
      - 3000:3000
    networks:
      - demo-network
    links:
      - message_db
      - read_model_db
    depends_on:
      - message_db
      - read_model_db

  message_db:
    image: articulate/message-db:1.2.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - demo-network
    ports:
      - 5432:5432
    expose:
      - 5432

  read_model_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["-p", "5433"]
    ports:
      - 5433:5433
    expose:
      - 5433
    networks:
      - demo-network


networks:
  demo-network:
    driver: bridge
